spring:
  application:
    name: hogwarts-artifact-online
  cloud:
    vault:
      authentication: token
      token: ${VAULT_TOKEN}
      scheme: http
      host: 127.0.0.1
      port: 8200
      kv:
        enabled: true
  config:
    import: vault://
  datasource:
    url: ${datasource-url} #jdbc:h2:mem:hogwarts-dev
    username: ${datasource-username} #dev
    password: ${datasource-password} #dev
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
ai:
  openai:
    endpoint: ${AI_OPENAI_ENDPOINT:https://api.openai.com/v1/chat/completions} #enviornment variable with default value
    api-key: ${AI_OPENAI_KEY:YOUR_API_KEY} #enviornment variable with default value
  theb:
    endpoint: ${AI_THEBAI_ENDPOINT:https://api.theb.ai/v1/chat/completions}
    api-key: ${AI_THEBAI_KEY:YOUR_API_KEY} #enviornment variable with default value