spring:
  datasource:
    url: ${datasource-url} #jdbc:h2:mem:hogwarts-prod
    username: ${datasource-username}
    password: ${datasource-password}
  jpa:
    hibernate:
      ddl-auto: none # turn off DDL auto generation